"""updated comment table

Revision ID: d38c299b722a
Revises: b4fba05f8229
Create Date: 2024-02-14 15:17:15.743414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38c299b722a'
down_revision = 'b4fba05f8229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
